### PR TITLE
🚨fix travis 🚨

### PR DESCRIPTION
**Pull request by jukefr**
It works now you can safely merge

Side note: I used python as it allows to do everything we need without any third party libs or anything like that which makes for a faster travis boot time and execution time, and also the relative ease of python makes it perfect for newcommers to contribute

### CODE REVIEW

**Comment by jukefr** [comment]
okay seems it works now just need to revert the json file

**Comment by jukefr** [comment]
json file was reverted test should pass now

**Comment by jukefr** [comment]
test passed we are good to go

**Comment by jukefr** [comment]
🔥be careful the every PR made before a merge of this fix on master will be marked as good even if it is not 🔥

**Comment by johncoleman83** [comment]
> 🔥be careful the every PR made before a merge of this fix on master will be marked as good even if it is not 🔥
Good observation, we / someone can create an issue to run the `python` script against every file, fix the inconsistencies, then push the updates.

**Comment by jukefr** [comment]
To run it against every that is already here simply remove the git diff and use a recursive glob pattern that simply looks for `.json` files.
I'm kind of lazy so I don't think I'll do alot more code on this repository ^^

**Pull request merged**
