### PR TITLE
API Draft

### LINKED ISSUE #610: Add a rest api
We have all this data we might as well start making it available :)

I propose we add a very simply API to access these JSON files.

Here is a basic spec idea :
Starting with our main route `/`

`/` -> listing of LETTERS (or anything really)
`/LETTER/` -> listing of WORDS that start with LETTER
`/LETTER/WORD` -> actual word definition

**maybe add a fuzzy search also**

It might be worth to take a look at `lowdb` and especially `json-server` that can offer an API in seconds with a json file. I am unsure if it works with multiple files out of the box.

The main idea would be to keep the data as is (so no unique id added in the files or something like that) to make contributing stay as easy as possible.

As for deployment I strongly recommend https://zeit.co/now as it is free, integrated with github and perfect for continuous release (and easy)

edit: 1GB bandwidth might be low

### PR DESCRIPTION
**Pull request by jukefr**
I only had like 10 minutes so I made it work, but its not really well written or anything

it also has no test whatsoever

fixes #610 

how it works :
```
/ -> hello world
/a -> listing of words that start with a
/afor -> returns aformentioned.json
/aformentioned -> returns aformentioned.json
/search/fo -> returns an array of words (no matter the first letter) that matches the query (fuzzy search)
```

### CODE REVIEW

**Comment by jukefr** [comment]
No idea what happened with travis

**Comment by Showndarya** [comment]
@jukefr 

I guess its checking the format of ```package.json```

**Comment by jukefr** [comment]
yeah i was actually thinking of doing it without any node_modules but I didnt have the time to bootstrap a quick native xhr framework

i like to have the least packages possible always no matter the lang

**Comment by Showndarya** [comment]
I'll merge this. Thanks !

**Comment by jukefr** [comment]
I also messed up the async/awaits everywhere
It can be optimized alot but works

**Comment by jukefr** [comment]
do you have an ideas for deployment ?

**Comment by Showndarya** [comment]
Ya. I thought of Heroku when I started off. Zeit will do too

**Comment by jukefr** [comment]
The problem with heroku is that you cannot have uptime of 24/7 only 8 hours a day if i remember otherwise I would have gone with heroku

**Pull request merged**
