### PR TITLE
Walk

### PR DESCRIPTION
**Pull request by nomitpahuja**
The Pull Request resolves Issue #273 

Description:
A brief description about the addition or edits made.

Notes: Delete all the text including this!
* The `#273` should be replaced with the specific Issue being referenced.

### CODE REVIEW

**Comment by Showndarya** [comment]
Hey @nomitpahuja 

Can you create a new Pull Request just for ```Walk.json``` ?
There is a conflict because of your previous commit.

Thanks for contributing

**Comment by nomitpahuja** [comment]
yeah cool, no problem!

**Comment by Showndarya** [comment]
I am closing this Pull Request. Do create a new Pull request for ```Walk.json```

**Comment by nomitpahuja** [comment]
i'll do it in 45 minutes

**Pull request closed without merging**
